version: "3.4"

services:
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin1234

    postgresdb:
        container_name: postgresdb
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=Postgresdb
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgres/data/

    pgadmin:
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        ports:
            - "8080:80"
        volumes:
            - pgadmin_data:/root/.pgadmin

    backend.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:DatabaseSettings=Server=postgresdb;Port=5432;Database=Postgresdb;UserId=admin;Password=admin1234;"
            - "RabbitMqConfig:HostName=rabbitmq"
        depends_on:
            - postgresdb
            - rabbitmq
        ports:
            - "7171:80"
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
